/**
 * Build-time script for Vercel deployment.
 * Reads OPENAI_API_KEY from Vercel Environment Variables
 * and generates js/secrets.js so the frontend can use it.
 *
 * Local dev: keep your real key in js/secrets.js (gitignored).
 * Vercel:   this script creates js/secrets.js from the env var.
 */
const fs = require('fs');
const path = require('path');

const secretsPath = path.join(__dirname, '..', 'js', 'secrets.js');
const apiKey = process.env.OPENAI_API_KEY || '';

if (!apiKey) {
  console.warn('⚠️  OPENAI_API_KEY env var not set — AI features will be disabled.');
}

const content = [
  '// ============================================================',
  '// Secrets — Auto-generated by Vercel build script',
  '// ============================================================',
  '',
  `CONFIG.openai.apiKey = '${apiKey}';`,
  ''
].join('\n');

fs.writeFileSync(secretsPath, content, 'utf-8');
console.log(`✅ Generated js/secrets.js (${apiKey ? 'key injected' : 'empty fallback'})`);