// ============================================================
// inject-env.js — Vercel build script
// Generates js/secrets.js from OPENROUTER_API_KEY env var
// ============================================================
const fs = require('fs');
const path = require('path');

const apiKey = process.env.OPENROUTER_API_KEY;

if (!apiKey) {
  console.log('⚠️  OPENROUTER_API_KEY not set — skipping secrets.js generation');
  console.log('   Fill-in-the-blank AI will use fallback sentences.');
  process.exit(0);
}

const content = `// ============================================================
// Secrets — Auto-generated by Vercel build (DO NOT EDIT)
// ============================================================

CONFIG.openrouter.apiKey = '${apiKey.replace(/'/g, "\\'")}';
`;

const outPath = path.join(__dirname, '..', 'js', 'secrets.js');
fs.writeFileSync(outPath, content, 'utf-8');
console.log('✅  js/secrets.js generated from OPENROUTER_API_KEY');